# Wazuh Cluster - Highly availability design with multiple nodes
nodes:
  # Wazuh indexer nodes
  indexer:
    - name: node-1
      ip: "wzindexernode01.securemindacademy.com"
    - name: node-2
      ip: "wzindexernode02.securemindacademy.com"
    - name: node-3
      ip: "wzindexernode03.securemindacademy.com"

  # Wazuh server nodes
  # If there is more than one Wazuh server
  # node, each one must have a node_type
  server:
    - name: wazuh-1
      ip: "wzmanagernode.securemindacademy.com"
      node_type: master
    - name: wazuh-2
      ip: "wzworkernode.securemindacademy.com"
      node_type: worker
    #- name: wazuh-3
    #  ip: "<wazuh-manager-ip>"
    #  node_type: worker

  # Wazuh dashboard nodes
  dashboard:
    - name: dashboard
      ip: "wzdashboard.securemindacademy.com"
